# Generated by Django 3.2.18 on 2023-03-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_announcedpuresults_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='announcedpuresults',
            name='polling_unit_uniqueid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pollingunit'),
        ),
    ]
